// Generated by CoffeeScript 2.4.1
(function() {
  var ceil, floor, gcd, lcm, mainConfig;

  mainConfig = {
    '1.0': {
      version: '1.0',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 24,
      threadsPerMultiprocessor: 768,
      threadBlocksPerMultiprocessor: 8,
      sharedMemoryPerMultiprocessor: 16384,
      registerFileSize: 8192,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'block',
      maxRegistersPerThread: 124,
      sharedMemoryAllocationUnitSize: 512,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 512
    },
    '1.1': {
      version: '1.1',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 24,
      threadsPerMultiprocessor: 768,
      threadBlocksPerMultiprocessor: 8,
      sharedMemoryPerMultiprocessor: 16384,
      registerFileSize: 8192,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'block',
      maxRegistersPerThread: 124,
      sharedMemoryAllocationUnitSize: 512,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 512
    },
    '1.2': {
      version: '1.2',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 32,
      threadsPerMultiprocessor: 1024,
      threadBlocksPerMultiprocessor: 8,
      sharedMemoryPerMultiprocessor: 16384,
      registerFileSize: 16384,
      registerAllocationUnitSize: 512,
      allocationGranularity: 'block',
      maxRegistersPerThread: 124,
      sharedMemoryAllocationUnitSize: 512,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 512
    },
    '1.3': {
      version: '1.3',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 32,
      threadsPerMultiprocessor: 1024,
      threadBlocksPerMultiprocessor: 8,
      sharedMemoryPerMultiprocessor: 16384,
      registerFileSize: 16384,
      registerAllocationUnitSize: 512,
      allocationGranularity: 'block',
      maxRegistersPerThread: 124,
      sharedMemoryAllocationUnitSize: 512,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 512
    },
    '2.0': {
      version: '2.0',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 48,
      threadsPerMultiprocessor: 1536,
      threadBlocksPerMultiprocessor: 8,
      sharedMemoryPerMultiprocessor: 49152,
      registerFileSize: 32768,
      registerAllocationUnitSize: 64,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 63,
      sharedMemoryAllocationUnitSize: 128,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 1024
    },
    '2.1': {
      version: '2.1',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 48,
      threadsPerMultiprocessor: 1536,
      threadBlocksPerMultiprocessor: 8,
      sharedMemoryPerMultiprocessor: 49152,
      registerFileSize: 32768,
      registerAllocationUnitSize: 64,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 63,
      sharedMemoryAllocationUnitSize: 128,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 1024
    },
    '3.0': {
      version: '3.0',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 16,
      sharedMemoryPerMultiprocessor: 49152,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 63,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '3.5': {
      version: '3.5',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 16,
      sharedMemoryPerMultiprocessor: 49152,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '3.7': {
      version: '3.7',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 16,
      sharedMemoryPerMultiprocessor: 114688,
      registerFileSize: 131072,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '5.0': {
      version: '5.0',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 65536,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '5.2': {
      version: '5.2',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 98304,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '5.3': {
      version: '5.3',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 65536,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '6.0': {
      version: '6.0',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 65536,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 1024
    },
    '6.1': {
      version: '6.1',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 98304,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '6.2': {
      version: '6.2',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 65536,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '7.0': {
      version: '7.0',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 64,
      threadsPerMultiprocessor: 2048,
      threadBlocksPerMultiprocessor: 32,
      sharedMemoryPerMultiprocessor: 98304,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 4,
      maxThreadBlockSize: 1024
    },
    '7.5': {
      version: '7.5',
      threadsPerWarp: 32,
      warpsPerMultiprocessor: 32,
      threadsPerMultiprocessor: 1024,
      threadBlocksPerMultiprocessor: 16,
      sharedMemoryPerMultiprocessor: 65536,
      registerFileSize: 65536,
      registerAllocationUnitSize: 256,
      allocationGranularity: 'warp',
      maxRegistersPerThread: 255,
      sharedMemoryAllocationUnitSize: 256,
      warpAllocationGranularity: 2,
      maxThreadBlockSize: 1024
    }
  };

  gcd = function(a, b) {
    while (b !== 0) {
      [a, b] = [b, a % b];
    }
    // b = a % b
    // a = t
    return a;
  };

  lcm = function(a, b) {
    return a * b / gcd(a, b);
  };

  ceil = function(a, b) {
    return Math.ceil(a / b) * b;
  };

  floor = function(a, b) {
    return Math.floor(a / b) * b;
  };

  window.calculate = function(input) {
    var activeThreadBlocksPerMultiprocessor, activeThreadsPerMultiprocessor, activeWarpsPerMultiprocessor, blockRegisters, blockSharedMemory, blockWarps, config, multiprocessorRegisters, occupancyOfMultiprocessor, output, threadBlocksPerMultiprocessorLimitedByRegistersPerMultiprocessor, threadBlocksPerMultiprocessorLimitedBySharedMemoryPerMultiprocessor, threadBlocksPerMultiprocessorLimitedByWarpsOrBlocksPerMultiprocessor;
    config = mainConfig[input.version];
    blockWarps = function() {
      return Math.ceil(input.threadsPerBlock / config.threadsPerWarp);
    };
    blockRegisters = function() {
      if (config.allocationGranularity === 'block') {
        return ceil(ceil(blockWarps(), config.warpAllocationGranularity) * input.registersPerThread * config.threadsPerWarp, config.registerAllocationUnitSize);
      } else {
        //Correct value is given, xls value is commented (no of warps per block)
        // debugger
        return ceil(input.registersPerThread * config.threadsPerWarp, config.registerAllocationUnitSize) * blockWarps();
      }
    };
    //blockWarps()
    multiprocessorRegisters = function() {
      if (config.allocationGranularity === 'block') {
        return config.registerFileSize;
      } else {
        //Correct value is given, xls value is commented (no of warps per Multiprocessor)
        return floor(config.registerFileSize / ceil(input.registersPerThread * config.threadsPerWarp, config.registerAllocationUnitSize), config.warpAllocationGranularity) * ceil(input.registersPerThread * config.threadsPerWarp, config.registerAllocationUnitSize);
      }
    };
    //floor( config.registerFileSize/ ceil(input.registersPerThread * config.threadsPerWarp, config.registerAllocationUnitSize), config.warpAllocationGranularity )
    blockSharedMemory = function() {
      return ceil(input.sharedMemoryPerBlock, config.sharedMemoryAllocationUnitSize);
    };
    threadBlocksPerMultiprocessorLimitedByWarpsOrBlocksPerMultiprocessor = function() {
      return Math.min(config.threadBlocksPerMultiprocessor, Math.floor(config.warpsPerMultiprocessor / blockWarps()));
    };
    threadBlocksPerMultiprocessorLimitedByRegistersPerMultiprocessor = function() {
      if (input.registersPerThread > config.maxRegistersPerThread) {
        return 0;
      } else {
        if (input.registersPerThread > 0) {
          //Math.floor( config.registerFileSize  / blockRegisters())
          return Math.floor(multiprocessorRegisters() / blockRegisters());
        } else {
          return config.threadBlocksPerMultiprocessor;
        }
      }
    };
    threadBlocksPerMultiprocessorLimitedBySharedMemoryPerMultiprocessor = function() {
      if (input.sharedMemoryPerBlock > 0) {
        return Math.floor(config.sharedMemoryPerMultiprocessor / blockSharedMemory());
      } else {
        return config.threadBlocksPerMultiprocessor;
      }
    };
    activeThreadsPerMultiprocessor = function() {
      return input.threadsPerBlock * activeThreadBlocksPerMultiprocessor();
    };
    activeWarpsPerMultiprocessor = function() {
      return activeThreadBlocksPerMultiprocessor() * blockWarps();
    };
    activeThreadBlocksPerMultiprocessor = function() {
      return Math.min(threadBlocksPerMultiprocessorLimitedByWarpsOrBlocksPerMultiprocessor(), threadBlocksPerMultiprocessorLimitedByRegistersPerMultiprocessor(), threadBlocksPerMultiprocessorLimitedBySharedMemoryPerMultiprocessor());
    };
    occupancyOfMultiprocessor = function() {
      return activeWarpsPerMultiprocessor() / config.warpsPerMultiprocessor;
    };
    output = {
      activeThreadsPerMultiprocessor: activeThreadsPerMultiprocessor(),
      activeWarpsPerMultiprocessor: activeWarpsPerMultiprocessor(),
      activeThreadBlocksPerMultiprocessor: activeThreadBlocksPerMultiprocessor(),
      occupancyOfMultiprocessor: occupancyOfMultiprocessor(),
      blockWarps: blockWarps(),
      blockSharedMemory: blockSharedMemory(),
      blockRegisters: blockRegisters(),
      threadBlocksPerMultiprocessorLimitedByWarpsOrBlocksPerMultiprocessor: threadBlocksPerMultiprocessorLimitedByWarpsOrBlocksPerMultiprocessor(),
      threadBlocksPerMultiprocessorLimitedByRegistersPerMultiprocessor: threadBlocksPerMultiprocessorLimitedByRegistersPerMultiprocessor(),
      threadBlocksPerMultiprocessorLimitedBySharedMemoryPerMultiprocessor: threadBlocksPerMultiprocessorLimitedBySharedMemoryPerMultiprocessor()
    };
    output = _.extend(output, config);
    return output;
  };

  window.calculateGraphs = function(input) {
    var config, graphWarpOccupancyOfRegistersPerThread, graphWarpOccupancyOfSharedMemoryPerBlock, graphWarpOccupancyOfThreadsPerBlock, output;
    config = mainConfig[input.version];
    graphWarpOccupancyOfThreadsPerBlock = function() {
      var current, i, inp, r, ref, threadsPerBlock;
      current = {
        threadsPerBlock: input.threadsPerBlock,
        activeWarpsPerMultiprocessor: window.calculate(input).activeWarpsPerMultiprocessor
      };
      inp = _.clone(input);
      r = [];
      for (threadsPerBlock = i = 32, ref = config.maxThreadBlockSize; i <= ref; threadsPerBlock = i += 32) {
        inp.threadsPerBlock = threadsPerBlock;
        r.push({
          threadsPerBlock: threadsPerBlock,
          activeWarpsPerMultiprocessor: window.calculate(inp).activeWarpsPerMultiprocessor
        });
      }
      return {
        xlabel: "Threads Per Block",
        data: r,
        current: current
      };
    };
    graphWarpOccupancyOfRegistersPerThread = function() {
      var current, i, inp, r, ref, registersPerThread;
      current = {
        registersPerThread: input.registersPerThread,
        activeWarpsPerMultiprocessor: window.calculate(input).activeWarpsPerMultiprocessor
      };
      inp = _.clone(input);
      r = [];
      for (registersPerThread = i = 1, ref = config.maxRegistersPerThread; (1 <= ref ? i <= ref : i >= ref); registersPerThread = 1 <= ref ? ++i : --i) {
        inp.registersPerThread = registersPerThread;
        r.push({
          registersPerThread: registersPerThread,
          activeWarpsPerMultiprocessor: window.calculate(inp).activeWarpsPerMultiprocessor
        });
      }
      return {
        xlabel: "Registers Per Thread",
        data: r,
        current: current
      };
    };
    graphWarpOccupancyOfSharedMemoryPerBlock = function() {
      var current, i, inp, r, ref, sharedMemoryPerBlock;
      current = {
        sharedMemoryPerBlock: input.sharedMemoryPerBlock,
        activeWarpsPerMultiprocessor: window.calculate(input).activeWarpsPerMultiprocessor
      };
      inp = _.clone(input);
      r = [];
      for (sharedMemoryPerBlock = i = 0, ref = config.sharedMemoryPerMultiprocessor; i <= ref; sharedMemoryPerBlock = i += 512) {
        inp.sharedMemoryPerBlock = sharedMemoryPerBlock;
        r.push({
          sharedMemoryPerBlock: sharedMemoryPerBlock,
          activeWarpsPerMultiprocessor: window.calculate(inp).activeWarpsPerMultiprocessor
        });
      }
      return {
        xlabel: "Shared Memory Per Block",
        data: r,
        current: current
      };
    };
    return output = {
      graphWarpOccupancyOfThreadsPerBlock: graphWarpOccupancyOfThreadsPerBlock(),
      graphWarpOccupancyOfRegistersPerThread: graphWarpOccupancyOfRegistersPerThread(),
      graphWarpOccupancyOfSharedMemoryPerBlock: graphWarpOccupancyOfSharedMemoryPerBlock()
    };
  };

}).call(this);
